version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672" # Porta da interface de gerenciamento web
      - "5672:5672"   # Porta padrão do RabbitMQ para clientes AMQP
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: always

volumes:
  rabbitmq-data:
