version: '3'
services:
  mongodb:
    image: mongo:latest # Use a imagem mais recente do MongoDB do Docker Hub
    container_name: mongodb # Nome do contêiner MongoDB
    ports:
      - "27017:27017" # Mapeamento da porta do host para a porta do contêiner MongoDB
    volumes:
      - mongodb_data:/data/db # Volume para armazenar os dados do MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: myusername # Nome de usuário do MongoDB (opcional)
      MONGO_INITDB_ROOT_PASSWORD: mypassword # Senha do MongoDB (opcional)
    networks:
      - mynetwork # Nome da rede para conectar o contêiner

volumes:
  mongodb_data:
    # Definição do volume para armazenar os dados

networks:
  mynetwork:
    # Definição da rede para conectar os contêineres
    driver: bridge
